apiVersion: v1
kind: Service
metadata:
  labels:
    app: conprof
  name: conprof-main-governing-service
  namespace: observatorium
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app: conprof
